export const FETCH_SYSORG_LIST = 'FETCH_SYSORG_LIST';
export const RECEIVE_SYSORG_LIST = 'RECEIVE_SYSORG_LIST';
export const FETCH_PROVINCE_LIST = 'FETCH_PROVINCE_LIST';
export const RECEIVE_PROVINCE_LIST = 'RECEIVE_PROVINCE_LIST';